version: "3.8"

services:
  caddy:
    networks:
      - speknet
    image: caddy:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    env_file:
      - caddy.env
  api:
    networks:
      - speknet
    image: irere/spek:latest
    env_file:
      - spek.env
  postgres:
    networks:
      - speknet
    env_file:
      - pg.env
  rabbitmq:
    networks:
      - speknet
    env_file:
      - rabbit.env
  adminer:

volumes:
  caddy_data:
  caddy_config:
networks:
  speknet:
