version: "3.8"

services:
  caddy:
    networks:
      - spek-net
    image: caddy:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
  api:
    networks:
      - spek-net
    image: irere/spek:latest
    env_file:
      - spek.env
  postgres:
    networks:
      - spek-net
    env_file:
      - pg.env
  rabbitmq:
    networks:
      - spek-net
    env_file:
      - rabbit.env

volumes:
  caddy_data:
  caddy_config:
networks:
  - spek-net
