# On local the containers will be built locally and tagged, able to be published.
# On prod the compose file will pull from the docker registry
services:
  rabbitmq:
    image: rabbitmq:3-management-alpine
    restart: unless-stopped
    labels:
      spek.description: "RabbitMQ broker"
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq/
      - rabbitmq-logs:/var/log/rabbitmq/
    ports:
      - 5672:5672
      - 15672:15672
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "-q", "ping"]
      interval: 60s
      timeout: 5s

  api:
    restart: unless-stopped
    labels:
      spek.description: "Backend Service"
    depends_on:
      - postgres
      - rabbitmq

  postgres:
    image: postgres:13-alpine
    restart: unless-stopped
    labels:
      spek.description: "Postgres Database"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - 5432:5432
  adminer:
    image: adminer
    restart: unless-stopped
    ports:
      - 8080:8080
    labels:
      spek.description: "Adminer Database"
    depends_on:
      - postgres

volumes:
  postgres-data:
  rabbitmq-data:
  rabbitmq-logs:
