name: api:deploy_staging
on:
  push:
    paths:
      - "api/**"
      - ".github/**"
    branches:
      - master

jobs:
  deployment:
    name: Build
    runs-on: ubuntu-latest
    environment: api
    steps:
      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          script: sudo -i && "${{ vars.HOST_PASSWORD }}" && cd spek/api && git pull origin master && docker build -t irere/spek:0.0.1 . && docker tag irere/spek:0.0.1 dokku/spek-api:latest && dokku tags:deploy spek-api latest
