name: Build VC Docker Image
on:
  push:
    paths:
      - "horizon/**"
    branches:
      - prod

jobs:
  docker:
    name: "Docker build"
    runs-on: ubuntu-latest
    environment: api
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: ./horizon
          file: ./horizon/Dockerfile
          push: true
          tags: irere/horizon:latest
